from django.urls import path, include
from core.views import (RetrieveCommentatorView, FollowCommentatorView, CommentView, NotificationView, SubscriptionView,
                         CommentReactionView, ProfileView, FavEditorsCreateView, RetrieveFavEditorsAndFavComment,
                         SupportView, UpdateTicketMessageView, ResolvedTicket, ActiveResolvedCommentRetrieveView, ReplyTicketView,
                         TicketRedirectView, RetrieveSubUserView, SubUserSupportTicket,RedirectAnswerView,ShowTicketData, SportsStatisticsView,
        
                         RetrieveSubscriberListAndSubscriptionList, DeactivateProfile, SignupView, OtpVerify, OtpReSend, LoginView, PasswordResetView, RetrieveSubscriberListAndSubscriptionList, DeactivateProfile, OtpSend,
                         GoogleLoginview, FacebookLoginview, VerifyUserView, SignupUserExistsView, FootbalAndBasketballContentView)


from core.views import (AdminMainPage, UserManagement, FilterUserManagement, CommentsManagement, FilterComments, EditorManagement, EditorSubscriptionDetails,
                        FilterEditors, DeactivateCommentator, SalesManagement, SupportManagement, NotificationManagement,
                        SubUserManagement, AdvertisementManagement, LevelRule, MembershipSettingView, SubscriptionSettingView,
                        HighlightSettingView, CommentSetting, FilterSalesManagement, UpdateStatusForVerifyRequest, SubUserShowTicketData, 
                        UserStatistics, BecomeEditorView, BecomeEditorEarnDetailsview, GetALLUsers, RetrieveHomeView, RetrieveEditorView, BecomeEditorFAQView, FilterSubUserManagement)


urlpatterns = [
    path('facebook-login/', FacebookLoginview.as_view(), name='facebook-login'),
    path('google-login/', GoogleLoginview.as_view(), name='google-login'),
    path('signup/', SignupView.as_view(), name='Signup'),
    path('signup-user-exists/', SignupUserExistsView.as_view(), name='Signup-check-user-exists'),
    path('login/', LoginView.as_view(), name='Login'),
    path('otp-verify/', OtpVerify.as_view(), name='Otp-Verify'),
    path('otp-resend/', OtpReSend.as_view(), name='Otp-Resend'),
    path('password-reset/', PasswordResetView.as_view(), name='Otp-Resend'),
    path('retrieve-commentator/', RetrieveCommentatorView.as_view(), name='Retrieve-Commentator'),
    path('follow-commentator/<int:id>', FollowCommentatorView.as_view(), name='Follow-Commentator'),
    path('subscription/<int:id>/', SubscriptionView.as_view(), name='Subscription'),
    path('post-comment/<int:id>', CommentView.as_view(), name='Post-Comment'),
    path('post-comment/<int:pk>/', CommentView.as_view(), name='Update-Comment'),
    path('notification/<int:id>', NotificationView.as_view(), name='Notification'),
    path('comment-reaction/<int:comment_id>/<int:id>', CommentReactionView.as_view(), name='Comment-Reaction'),
    path('profile/<int:id>', ProfileView.as_view(), name='Profile'),
    path('fav-editor/<int:id>/', FavEditorsCreateView.as_view(), name='FavEditors'),
    path('fav-editor/', FavEditorsCreateView.as_view(), name='FavEditors'),
    path('fav-editor-comment/<int:id>', RetrieveFavEditorsAndFavComment.as_view(), name='FavEditors-FavComment'),
    path('support/<int:id>', SupportView.as_view(), name='Support'),
    path('update-support-ticket/', UpdateTicketMessageView.as_view(), name='Update-Ticket-Message'),
    path('reply-ticket/<int:id>/<int:ticket_id>/', ReplyTicketView.as_view(), name='Reply-Ticket'),
    path('resolved-ticket/<int:id>', ResolvedTicket.as_view(), name='Resolved-Ticket'),
    path('active-resolved-comment/<int:id>', ActiveResolvedCommentRetrieveView.as_view(), name='Active-Resolved-Comment-Retrieve'),
    path('retrieve-subscribers-subscription/<int:id>', RetrieveSubscriberListAndSubscriptionList.as_view(), name='SubscriberList-SubscriptionList'),
    path('deactivate-profile/', DeactivateProfile.as_view(), name='Deactivate-Profile'),
    path('verify/<int:id>/', VerifyUserView.as_view(), name='Verify-User'),
    path('retrieve-redirect-user/', RetrieveSubUserView.as_view(), name='Retrieve-Sub-User'),
    path('redirect-ticket/<int:id>/<int:ticket_id>', TicketRedirectView.as_view(), name='Ticket-Redirect'),
    path('subuser-tickets/<int:id>/', SubUserSupportTicket.as_view(), name='SubUser-Support-Ticket'),
    path('subuser-redirect-ticket/<int:id>/<int:ticket_id>/', RedirectAnswerView.as_view(), name='Redirect-Answer'),
    path('subuser-answer-ticket/<int:id>/<int:ticket_id>/', ShowTicketData.as_view(), name='Show-Ticket-Data'),
    path('user-statistics/<int:id>/', UserStatistics.as_view(), name='user-statistics'), 
    # path("monthly_subscription_chart/<int:id>", MonthlySubScriptionChart.as_view(), name='monthly_subscription_chart'),
    path('sports-statistics/<int:id>/', SportsStatisticsView.as_view(), name='Sports-State'), 
    path('football-basketball-content/', FootbalAndBasketballContentView.as_view(), name='Football-Basketball-Content'), 


    # Admin Panel's api
    path('all-users/', GetALLUsers.as_view(), name='All-Users'),
    path('home/', AdminMainPage.as_view(), name='Main-Page'),
    path('filter-user-management/', FilterUserManagement.as_view(), name='Filter-User-Management'),
    path('user-management/', UserManagement.as_view(), name='UserManagement'),
    path('user-management/<int:pk>/', UserManagement.as_view(), name='User-Management'),
    path('comments-management/', CommentsManagement.as_view(), name='Comments-Management'),
    path('comments-management/<int:pk>/', CommentsManagement.as_view(), name='Updateomments'),
    path('filter-comments/<int:id>/', FilterComments.as_view(), name='Filter-Comments'),
    path('editor-management/', EditorManagement.as_view(), name='Editor-Management'),
    path('editor-management/<int:pk>/', EditorManagement.as_view(), name='Editor-Management'),
    path('editor-subscription-details/', EditorSubscriptionDetails.as_view(), name='Editor-Subscription-Details'),
    path('filter-editors/', FilterEditors.as_view(), name='Filter-Editors'),
    path('deactivate-commentator/', DeactivateCommentator.as_view(), name='Deactivate-Commentator'),
    path('deactivate-commentator/<int:id>/', DeactivateCommentator.as_view(), name='Deactivate-Commentator'),
    path('sales-management/', SalesManagement.as_view(), name='Sales-Management'),
    path('filter-sales-management/', FilterSalesManagement.as_view(), name='Filter-Sales-Management'),
    path('support-management/', SupportManagement.as_view(), name='Support-Management'),
    path('support-management/<int:id>/', SupportManagement.as_view(), name='Support-Management-Response'),
    path('notification-management/', NotificationManagement.as_view(), name='Notification-Management'),
    path('subuser-management/', SubUserManagement.as_view(), name='SubUser-Management'),
    path('subuser-management/<int:pk>/', SubUserManagement.as_view(), name='SubUser-Management'),
    path('filter-sub-user-management/', FilterSubUserManagement.as_view(), name='Filter-Sub-User-Management'),
    path('ads-management/', AdvertisementManagement.as_view(), name='Advertisement-Management'),
    path('ads-management/<int:pk>/', AdvertisementManagement.as_view(), name='Advertisement-Management'),
    path('level-rule/', LevelRule.as_view(), name='Level-Rule'),
    path('membership-setting/', MembershipSettingView.as_view(), name='Membership-Setting'),
    path('subscription-setting/', SubscriptionSettingView.as_view(), name='Subscription-Setting'),
    path('highlight-setting/', HighlightSettingView.as_view(), name='Highlight-Setting'),
    path('comment-setting/', CommentSetting.as_view(), name='Comment-Setting'),
    path('verify-user/', UpdateStatusForVerifyRequest.as_view(), name='Update-Status-For-Verify-Request'),
    path('verify-user/<int:id>/', UpdateStatusForVerifyRequest.as_view(), name='Update-Status-For-Verify-Request'),
    path('show-ticket-data/<int:ticket_id>/', SubUserShowTicketData.as_view(), name='Show-Ticket-Data'),
    # path('become-editor/', BecomeEditorView.as_view(), name='become-editor'),
    path('become-editor/<int:id>/', BecomeEditorView.as_view(), name='Become-Editor'),
    path('become-editor-earn-details/<int:subscriber>/', BecomeEditorEarnDetailsview.as_view(), name='become-editor-earn-details'),

    # path('become-editor-earn-details/', BecomeEditorEarnDetailsview.as_view(), name='become-editor-earn-details'),
    # path('become-editor-earn-details/<int:id>/', BecomeEditorEarnDetailsview.as_view(), name='become-editor-earn-details'),
    # path('become-editor-earn-details/<int:id>/<int:subscriber>/', BecomeEditorEarnDetailsview.as_view(), name='become-editor-earn-details'),

    path('retrieve-dashboard/', RetrieveHomeView.as_view(), name='Retrieve-Home'),
    path('retrieve-commentator-list/', RetrieveEditorView.as_view(), name='Retrieve-Editor'),
    path('become-editor-faq/', BecomeEditorFAQView.as_view(), name='become-editor'),
    path('become-editor-faq/<int:id>', BecomeEditorFAQView.as_view(), name='become-editor'),
]
