# Generated by Django 4.2.3 on 2023-07-18 06:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=12)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), default=list, size=None)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('user_role', models.CharField(choices=[('standard', 'Standard'), ('commentator', 'Commentator')], default='standard', max_length=20)),
                ('commentator_level', models.CharField(blank=True, choices=[('apprentice', 'Apprentice'), ('journeyman', 'Journeyman'), ('master', 'Master'), ('grandmaster', 'Grandmaster')], max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
