# Generated by Django 4.2.3 on 2023-07-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowCommentator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commentator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator_user', to='core.user')),
                ('standard_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_user', to='core.user')),
            ],
        ),
    ]
