# Generated by Django 4.2.3 on 2023-07-18 11:48

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_followcommentator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), default=list, size=None)),
                ('country', models.CharField(max_length=50)),
                ('league', models.CharField(max_length=120)),
                ('date', models.DateField(default=datetime.date.today)),
                ('match_detail', models.CharField(max_length=120)),
                ('prediction_type', models.CharField(max_length=120)),
                ('prediction', models.CharField(max_length=120)),
                ('public_content', models.BooleanField()),
                ('comment', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commentator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
