# Generated by Django 4.2.3 on 2023-07-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject')], default='pending', max_length=20),
        ),
    ]
