# Generated by Django 4.2.3 on 2023-07-19 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comments_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.BooleanField()),
                ('duration', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 54, 36, 51418))),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commentator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator', to='core.user')),
                ('standard_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard', to='core.user')),
            ],
        ),
    ]
