# Generated by Django 4.2.3 on 2023-08-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_in_using',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
