# Generated by Django 4.2.3 on 2023-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bluetick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomecommentator',
            name='money',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='becomecommentator',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
