# Generated by Django 4.2.3 on 2023-07-24 09:54

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subscription_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 9, 54, 10, 877003)),
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('progress', 'Progress'), ('resolved', 'Resolved'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('chat', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavEditors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commentator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator1', to='core.user')),
                ('standard_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard1', to='core.user')),
            ],
        ),
    ]
