# Generated by Django 4.2.3 on 2023-08-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_becomecommentator_money_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('editor', models.IntegerField(default=0)),
                ('subscription', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
                ('highlight', models.IntegerField(default=0)),
                ('advertisement', models.IntegerField(default=0)),
                ('comment_win', models.IntegerField(default=0)),
                ('comment_lose', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
