# Generated by Django 4.2.3 on 2023-08-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_datacount'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacount',
            name='ticket',
            field=models.IntegerField(default=0),
        ),
    ]
