# Generated by Django 4.2.3 on 2023-08-21 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_logged_in_using'),
        ('core', '0010_user_is_delete'),
    ]

    operations = [
    ]
