# Generated by Django 4.2.3 on 2023-07-26 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_subscription_start_date_deactivatecommentator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivate_commentator',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 4, 26, 38, 253909)),
        ),
        migrations.DeleteModel(
            name='DeactivateCommentator',
        ),
    ]
