# Generated by Django 4.2.3 on 2023-08-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notification_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('create', 'Create'), ('comment_by_user', 'Comment_by_user'), ('request_for_update', 'Request_for_update')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_request', to='core.user')),
                ('response_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.responseticket')),
                ('ticket_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ticketsupport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_create', to='core.user')),
            ],
        ),
    ]
