# Generated by Django 4.2.3 on 2023-07-26 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_deactivate_commentator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreaction',
            name='reaction',
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='clap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='favorite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 5, 17, 36, 33782)),
        ),
    ]
