# Generated by Django 4.2.3 on 2023-08-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tickethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='request_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_request', to='core.user'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_create', to='core.user'),
        ),
    ]
