# Generated by Django 4.2.3 on 2023-08-21 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_tickethistory_request_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='response_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.responseticket'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='status',
            field=models.CharField(blank=True, choices=[('create', 'Create'), ('comment_by_user', 'Comment_by_user'), ('request_for_update', 'Request_for_update')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='ticket_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ticketsupport'),
        ),
    ]
