# Generated by Django 4.2.3 on 2023-07-27 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_gender_alter_subscription_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 10, 37, 32, 992943)),
        ),
    ]
