# Generated by Django 4.2.3 on 2023-08-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_tickethistory_response_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='redirect_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_ticket', to='core.user'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='status',
            field=models.CharField(blank=True, choices=[('create', 'Create'), ('comment_by_user', 'Comment_by_user'), ('request_for_update', 'Request_for_update'), ('redirect', 'Redirect')], default='pending', max_length=20, null=True),
        ),
    ]
