# Generated by Django 4.2.3 on 2023-08-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tickethistory_redirect_to_alter_tickethistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
