# Generated by Django 4.2.3 on 2023-07-31 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_last_login_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commentator_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('deactive', 'Deactive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 9, 57, 54, 443419)),
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comments')),
            ],
        ),
    ]
