# Generated by Django 4.2.3 on 2023-07-31 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_commentator_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='money',
            field=models.FloatField(default=220.9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 11, 58, 10, 533015)),
        ),
    ]
