# Generated by Django 4.2.3 on 2023-08-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tickethistory_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsupport',
            name='status',
            field=models.CharField(choices=[('progress', 'Progress'), ('resolved', 'Resolved'), ('pending', 'Pending'), ('update_message', 'Update_message')], default='pending', max_length=20),
        ),
    ]
