# Generated by Django 4.2.3 on 2023-08-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_ticketsupport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsupport',
            name='status',
            field=models.CharField(choices=[('progress', 'Progress'), ('resolved', 'Resolved'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
