# Generated by Django 4.2.3 on 2023-08-01 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_subscription_money_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='highlight',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlight',
            name='money',
            field=models.FloatField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 8, 15, 39, 335917)),
        ),
    ]
