# Generated by Django 4.2.3 on 2023-08-01 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_highlight_highlight_highlight_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('deactive', 'Deactive')], default='active', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 9, 38, 52, 213424)),
        ),
    ]
