# Generated by Django 4.2.3 on 2023-08-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_ticketsupport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
