# Generated by Django 4.2.3 on 2023-08-02 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_highlight_status_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(default='2023-07-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='subscription', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 3, 55, 4, 400315)),
        ),
    ]
