# Generated by Django 4.2.3 on 2023-08-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('answer', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='BecomeEditorEarnDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(blank=True, choices=[('journeyman', 'Journeyman'), ('master', 'Master'), ('grandmaster', 'Grandmaster')], max_length=20, null=True, unique=True)),
                ('threshold_subscriber', models.IntegerField()),
                ('earn_amount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='average_odds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='is_prediction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='is_resolve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(choices=[('1-2 years', '1-2 years'), ('3-4 years', '3-4 years'), ('5+ years', '5+ years'), ('10+ years', '10+ years')], default='1-2 years', max_length=20),
        ),
    ]
