# Generated by Django 4.2.3 on 2023-09-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_becomeeditor_becomeeditorearndetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='success_rate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
