# Generated by Django 4.2.3 on 2023-08-04 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_subscription_start_date_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 6, 14, 0, 607600)),
        ),
    ]
