# Generated by Django 4.2.3 on 2023-08-02 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_authorization_type_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sales_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 5, 18, 14, 251513)),
        ),
    ]
