# Generated by Django 4.2.3 on 2023-09-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_user_success_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='success_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
