# Generated by Django 4.2.3 on 2023-08-07 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('favorite', 'Favorite'), ('clap', 'Clap')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 4, 13, 54, 972744)),
        ),
    ]
