# Generated by Django 4.2.3 on 2023-08-07 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_commentreaction_reaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreaction',
            name='reaction',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 4, 30, 57, 490937)),
        ),
    ]
