# Generated by Django 4.2.3 on 2023-09-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_comments_is_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score_points',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
