# Generated by Django 4.2.3 on 2023-08-02 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_subscription_start_date_alter_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 5, 29, 18, 958093)),
        ),
    ]
