# Generated by Django 4.2.3 on 2023-09-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_is_verified_alter_user_success_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
