# Generated by Django 4.2.3 on 2023-09-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_score_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score_points',
            field=models.IntegerField(),
        ),
    ]
