# Generated by Django 4.2.3 on 2023-09-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_user_is_verified'),
        ('core', '0026_alter_user_score_points'),
    ]

    operations = [
    ]
