# Generated by Django 4.2.3 on 2023-08-02 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_advertisement_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('end', 'End')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 6, 24, 4, 978939)),
        ),
    ]
