# Generated by Django 4.2.3 on 2023-08-02 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_advertisement_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('end', 'End')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 6, 43, 39, 929471)),
        ),
    ]
