# Generated by Django 4.2.3 on 2023-09-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20230904_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
