# Generated by Django 4.2.3 on 2023-08-02 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_advertisement_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentatorLevelRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_level', models.CharField(blank=True, choices=[('apprentice', 'Apprentice'), ('journeyman', 'Journeyman'), ('master', 'Master'), ('grandmaster', 'Grandmaster')], max_length=20, null=True)),
                ('daily_match_limit', models.IntegerField()),
                ('monthly_min_limit', models.IntegerField()),
                ('ods_limit', models.CharField(blank=True, max_length=50, null=True)),
                ('winning_limit', models.IntegerField()),
                ('sucess_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('subscriber_limit', models.CharField(blank=True, max_length=50, null=True)),
                ('level_icon', models.ImageField(blank=True, null=True, upload_to='level_icon')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 8, 14, 37, 404713)),
        ),
    ]
