# Generated by Django 4.2.3 on 2023-08-02 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_commentatorlevelrule_alter_subscription_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_level', models.CharField(blank=True, choices=[('apprentice', 'Apprentice'), ('journeyman', 'Journeyman'), ('master', 'Master'), ('grandmaster', 'Grandmaster')], max_length=20, null=True)),
                ('plan_price', models.FloatField()),
                ('commission_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('promotion_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('promotion_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 8, 57, 31, 264972)),
        ),
    ]
