# Generated by Django 4.2.3 on 2023-09-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_comments_is_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_clicks_and_redirected_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['created'], name='core_commen_created_56e5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created'], name='core_user_created_bf51fc_idx'),
        ),
    ]
