# Generated by Django 4.2.3 on 2023-09-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_comments_is_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, choices=[('1-2 years', '1-2 years'), ('3-4 years', '3-4 years'), ('5+ years', '5+ years'), ('10+ years', '10+ years')], max_length=20, null=True),
        ),

    ]
