# Generated by Django 4.2.3 on 2023-09-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_user_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_clicks_and_redirected_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
