# Generated by Django 4.2.3 on 2023-08-02 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_membershipsetting_alter_subscription_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_level', models.CharField(blank=True, choices=[('journeyman', 'Journeyman'), ('master', 'Master'), ('grandmaster', 'Grandmaster')], max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('month_1', models.FloatField()),
                ('month_3', models.FloatField()),
                ('month_6', models.FloatField()),
                ('year_1', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 9, 29, 30, 253695)),
        ),
    ]
