# Generated by Django 4.2.3 on 2023-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_advertisement_ad_clicks_and_redirected_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
