# Generated by Django 4.2.3 on 2023-08-02 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_subscriptionsetting_alter_subscription_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_level', models.CharField(blank=True, choices=[('journeyman', 'Journeyman'), ('master', 'Master'), ('grandmaster', 'Grandmaster')], max_length=20, null=True)),
                ('week_1', models.FloatField()),
                ('week_2', models.FloatField()),
                ('month_1', models.FloatField()),
                ('highlight_icon', models.ImageField(blank=True, null=True, upload_to='level_icon')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 9, 43, 9, 639049)),
        ),
    ]
