# Generated by Django 4.2.3 on 2023-09-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_user_experience_and_more'),
        ('core', '0030_comments_core_commen_created_56e5ed_idx_and_more'),
        # ('core', '0031_alter_advertisement_end_date_and_more'),
    ]

    operations = [
    ]
