# Generated by Django 4.2.3 on 2023-08-02 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_highlightsetting_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightsetting',
            name='highlight_icon',
            field=models.ImageField(blank=True, null=True, upload_to='highlight_icon'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 9, 45, 44, 498300)),
        ),
    ]
