# Generated by Django 4.2.3 on 2023-09-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20230912_0508'),
        ('core', '0032_user_description_and_more'),
    ]

    operations = [
    ]
