# Generated by Django 4.2.3 on 2023-08-02 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_highlightsetting_highlight_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 10, 30, 33, 255451)),
        ),
    ]
