# Generated by Django 4.2.3 on 2023-09-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_advertisement_ad_clicks_and_redirected_count_and_more'),
        ('core', '0033_merge_20230913_0354'),
    ]

    operations = [
    ]
