# Generated by Django 4.2.3 on 2023-09-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_merge_20230913_1035'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='is_active',
        #     field=models.BooleanField(default=True),
        # ),
    ]
