# Generated by Django 4.2.3 on 2023-08-02 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_commentreaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 10, 30, 35, 940143)),
        ),
    ]
