# Generated by Django 4.2.3 on 2023-09-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_advertisement_ad_clicks_and_redirected_count_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='user',
            name='deactivate_commentator',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], max_length=20, null=True),
        ),
      
    ]
