# Generated by Django 4.2.3 on 2023-09-15 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_advertisement_ad_clicks_and_redirected_count_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='becomeeditor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 15, 13, 19, 41, 969280, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='becomeeditor',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='becomeeditor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
       
        
        migrations.AlterField(
            model_name='becomeeditor',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='becomeeditor',
            name='question',
            field=models.TextField(),
        ),
        
    ]
