# Generated by Django 4.2.3 on 2023-09-27 04:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_advertisement_ad_clicks_and_redirected_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_iban', models.CharField(unique=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20, null=True)),
                ('total_balance', models.FloatField(blank=True, null=True)),
                ('pending_balance', models.FloatField(blank=True, null=True)),
                ('withdrawable_balance', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_clicks_and_redirected_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='match_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='context',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['created'], name='core_commen_created_56e5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created'], name='core_user_created_bf51fc_idx'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
