# Generated by Django 4.2.3 on 2023-09-29 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_bankdetails_editorbanner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_banner', models.ImageField(blank=True, null=True, upload_to='Editor_banner')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='admin_context',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
