# Generated by Django 4.2.3 on 2023-09-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_bankdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_banner', models.ImageField(blank=True, null=True, upload_to='Editor_banner')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
