# Generated by Django 4.2.3 on 2023-09-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_bankdetails_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='bankdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
       
    ]
