# Generated by Django 4.2.3 on 2023-09-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_notification_admin_context_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='advertisement',
        #     name='ad_clicks_and_redirected_count',
        #     field=models.IntegerField(default=0),
        # ),
        # migrations.AddField(
        #     model_name='advertisement',
        #     name='ad_views_count',
        #     field=models.IntegerField(default=0),
        # ),
        migrations.AddField(
            model_name='comments',
            name='match_time',
            field=models.TimeField(blank=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='user',
        #     name='description',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='is_active',
        #     field=models.BooleanField(default=True),
        # ),
        # migrations.AddIndex(
        #     model_name='comments',
        #     index=models.Index(fields=['created'], name='core_commen_created_56e5ed_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='user',
        #     index=models.Index(fields=['created'], name='core_user_created_bf51fc_idx'),
        # ),
    ]
