# Generated by Django 4.2.3 on 2023-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_advertisement_ad_clicks_and_redirected_count_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_iban',
            field=models.CharField(unique=True),
        ),
       
    ]
