# Generated by Django 4.2.3 on 2023-09-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_advertisement_ad_clicks_and_redirected_count_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='bankdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20, null=True),
        ),
        
    ]
